#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int bof(char *str)
{
    char buffer[100];

    // The vulnerable strcpy function
    strcpy(buffer, str);
    return 1;
}

int main(int argc, char **argv)
{
    char str[517];
    FILE *badfile;

    // Open the badfile generated by the exploit script
    badfile = fopen("badfile", "r");
    if (!badfile) {
        perror("Opening badfile");
        exit(1);
    }

    int length = fread(str, sizeof(char), 517, badfile);
    bof(str);

    printf("Returned Properly\n");
    return 1;
}
